const ERROR = {
  USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
  EMAIL_EXIST: 'EMAIL_EXIST',
  USER_NEED_TO_VERIFY_FIRST: 'USER_NEED_TO_VERIFY_FIRST',
  USER_BLOCKED: 'USER_BLOCKED',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  WRONG_VERIFY_CODE: 'WRONG_VERIFY_CODE',
  VERIFY_CODE_EXPIRED: 'VERIFY_CODE_EXPIRED',
  ADMIN_DOES_NOT_EXIST: 'ADMIN_DOES_NOT_EXIST',
  CAN_NOT_USE_THIS_LINK_ANYMORE: 'CAN_NOT_USE_THIS_LINK_ANYMORE',
  PRODUCT_DOES_NOT_EXIST: 'PRODUCT_DOES_NOT_EXIST',
  CAN_NOT_DELETE_THIS_PRODUCT: 'CAN_NOT_DELETE_THIS_PRODUCT',
  CATEGORIES_DOES_NOT_EXIST: 'CATEGORIES_DOES_NOT_EXIST',
  CAN_NOT_DELETE_THIS_CATEGORY: 'CAN_NOT_DELETE_THIS_CATEGORY',
  OUT_OF_STORAGE: 'OUT_OF_STORAGE',
  CART_ITEM_DOES_NOT_EXIST: 'CART_ITEM_DOES_NOT_EXIST',
  ORDER_DOES_NOT_EXIST: 'ORDER_DOES_NOT_EXIST',
  ORDER_HAS_BEEN_PAYED: 'ORDER_HAS_BEEN_PAYED',
};

module.exports = ERROR;
