const SUCCESS = {
  SUCCESS: 'SUCESS',
  CHANGE_PASSWORD_SUCCEED: 'CHANGE_PASSWORD_SUCCEED',
  YOUR_ORDER_HAS_BEEN_DELIVERING: 'Your order has been delivering',
  ORDER_HAS_BEEN_PAYED: 'ORDER_HAS_BEEN_PAYED',
};

module.exports = SUCCESS;
